mdias/urls.py
from django.conf.urls import patterns,  url
from mdias.views import PhotosList

urlpatterns = patterns('',
             url(r'photos/(?P<recent>\w+|)', PhotosList.as_view(), name = "photos")
             , 
              
              
              )

news/urls.py
from django.conf.urls import patterns, url

from news.views import  NewsDetailView, NewListView

urlpatterns = patterns('',
    url(r'(?P<slug>[\w-]+|)/$', NewsDetailView.as_view(),name= "story"),
    
    url(r'^$',NewListView.as_view(),name='news')               ,                 
   
                   
   # url(r'^about/$',views.about, name="about"),
    
)

polo/urls.py
from django.conf.urls import patterns, include, url
from sitemap import *
from django.contrib import admin
import publicpages.views
import nlsubscribers.views 
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'polo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
   # url('',publicpages.views.current_datetime,name="home"),
    
    url(r'^$', publicpages.views.current_datetime, name="home"),
    url(r'^about/$',publicpages.views.about, name="about"),
    url(r'^p1/$',publicpages.views.polo1, name="polo1"),
    url(r'^p2/$',publicpages.views.polo2, name="polo2"),
    url(r'^events/' ,include('events.urls',namespace="events")),
    url('^news/', include('news.urls',namespace='news')),
      url(r'^daguerre/', include('daguerre.urls')),
    url(r'^pages/' ,include('publicpages.urls', namespace="pages")),
    url(r'^teams/' ,include('teams.urls')),
    url(r'^sliders/' ,include('sliders.urls')),
    url(r'^multimedia/', include('mdias.urls',namespace='multimedia')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^manage/', include(admin.site.urls)),
    url(r'^nladd',nlsubscribers.views.nladd, name = "nladd"),
    
)


sitemaps = {
    'news':NewsSitemap,
    #'pages': FlatpageSitemap,
    #'site':SosaiSitemap(['home']),
    #['homepage_imprint', 'homepage_archive']
    #'site': Sitemap,
   
    'public': PublicPageSitemap
}


urlpatterns += patterns('',
                        (r'^sitemap\.xml', 'django.contrib.sitemaps.views.sitemap',
                         { 'sitemaps':sitemaps
     }),
    )
#for serving media files
from polo import settings

    
urlpatterns += patterns(
    'django.views.static',
    (r'media/(?P<path>.*)',
    'serve',
    {'document_root': settings.MEDIA_ROOT}), )


#for debug toolbar

if settings.SHOW_DEBUG_TOOLBAR:
    
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )
          

mdias/models.py
from django.db import models
from django.contrib.auth import get_user_model
from image_cropping import ImageRatioField, ImageCropField
from datetime import datetime


class Photos(models.Model):
    
    TAGS = (
        
        ('events','events'),
        ('polo','polo'),
        ('horses','horses'),
        ('racing','racing'),
        ('1212','1212'),
        ('people','people'),
        ('players','players'),
        ('games','games'),
        
    )
    class Meta:
        #app_label = 'Multimedia'
        verbose_name = 'Multimedia Photo'
        verbose_name_plural ='Multimedia Photos'
    photo = models.ImageField(blank=True, null=True, upload_to='multimedia_photos')  
    #photo = ImageCropField(blank=True, null=True, upload_to='multimedia_photos')
    # size is "width x height"
    photo_thumb = ImageRatioField('photo', '800x533')
    tag =  models.CharField(default = '1212', choices=TAGS,max_length=30)
    created = models.DateTimeField(auto_now=False, auto_now_add=True,default=datetime.now())
    modified = models.DateTimeField(auto_now=True, auto_now_add=False, default=datetime.now())
    user = models.ForeignKey(get_user_model())
    caption = models.CharField(blank= True, null=True,max_length=255)
    brief = models.TextField(blank=True, null=True)

mdias/views.py
from django.shortcuts import render
from django.views.generic import DetailView , ListView
from mdias.models import Photos
from datetime import datetime, timedelta,  date
 
class PhotosList(ListView):
    model = Photos
    template_name = 'mdias/photos.html'
    paginate_by = 20
    
    def get_context_data(self,  **kwargs):
        #print Photos.TAGS
        tag_list = []
        
        ctx = super(PhotosList,self).get_context_data(**kwargs)
        
        
        for j,v in Photos.TAGS:
            tag_list.append(j)
        tag_list = tag_list
        print(tag_list)
        ctx['tags'] =  set(tag_list)
        return ctx
    
    
    
    def get_queryset(self):
        today = datetime.now() 
        startdate = today + timedelta(days=-14) 
       
        queryset = super(PhotosList, self).get_queryset()
        if self.kwargs.get('recent') != "" :
            return queryset.filter(created__range=[startdate, today]).order_by('-created')
        else:
            return queryset.order_by('-created')
         
        return queryset

templates/mdias/photos.html
{% extends "homebase.html" %}

 {% load cropping %}
{% load staticfiles %}
  
{% block content %}
   
          
 <!-- Section Title -->
            <section class="section-title img-gallery">
                <div class="overlay-bg"></div> <div class="container">
                    <h1> Multimedia Photos </h1>
                </div>
            </section> <!-- End Section Title -->

            <!-- Section Area - Content Central --> <section
            class="content-info">

                <div class="crumbs">
                    <div class="container">
                        <ul>
                            <li><a href="index.html">Home</a></li> <li>/</li>
                            <li> Multimedia Photos </li>
                            
                                                            
                        </ul>
                    </div>
                </div>

                <div class="semiboxshadow text-center">
                    <img src="img/img-theme/shp.png" class="img-responsive"
                    alt="">
                </div>

                <!-- Content Central --> <div class="container">
                    <!-- Nav Filters --> <div class="portfolioFilter">
                        <a href="#" data-filter="*" class="current">Show All</a>
                         
                        {% for t in tags %}
                            <a href="#{{t}}"
                            data-filter=".{{t}}">{{t|title}}</a>
                        {% endfor %}
                    </div> <!-- End Nav Filters -->

                    <!-- Items Gallery filters--> <div
                    class="portfolioContainer">
                        {% for item in photos_list %} <!-- Item Gallery--> <div
                        class="col-xs-6 col-sm-6 col-md-3 {{item.tag }}">
                            <div class="img-hover">
                                <img src="{% cropped_thumbnail item "photo_thumb" %}" alt="" class="img-responsive">
                                <div class="overlay">
                                    {% if item.caption or item.brief %}
                                    <a rel="multimedia_photos" title="{{item.caption}}:: <br/> {{item.brief}}" href="{% cropped_thumbnail item "photo_thumb" %}"
                                class="fancybox">+</a>
                            {% else %}
                                
                                 <a rel="multimedia_photos"  href="{% cropped_thumbnail item "photo_thumb" %}"
                                class="fancybox">+</a>
                                 
                            {% endif %}
                                
                                </div>
                            </div>
                        </div> <!-- End Item Gallery-->
 
                       
                        
                    {% endfor %} </div> <!-- End Items Gallery filters-->
                    
                    
                  
 
 
 
 <!-- Pagination -->
 <ul class="pagination no-margin">
     {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">«</a></li>
  
{% endif %}
                                <li class="active"><a href="#">Pg {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                                {% for page in page_obj.paginator.page_range %}
     
   
     <li><a href="?page={{ page }}"> {{ page }}</a></li>
{% endfor %}
                                
                                
                                {% if page_obj.has_next %}
  
                                <li><a href="?page={{ page_obj.next_page_number }}">»</a></li>
                                
                                {% endif %}
                            </ul>
 <!-- End Pagination -->
                </div> <!-- End Content Central -->

                <!-- Newsletter -->
               {% include 'nl_subscriber.html' %}
                <!-- End Newsletter -->
            </section> <!-- End Section Area - Content Central -->
            
               
            
{% endblock %}