events/urls.py
from django.conf.urls import patterns,  url
from events.views import EventListView, EventDetailView

urlpatterns = patterns('',
            url(r'(?P<slug>[\w-]+|)/$', EventDetailView.as_view(),name= "event"),
    
  
              url(r'^$', EventListView.as_view(), name = "events")
              
              
              
              )

mdias/urls.py
from django.conf.urls import patterns,  url
from mdias.views import PhotosList

urlpatterns = patterns('',
             url(r'photos/(?P<recent>\w+|)', PhotosList.as_view(), name = "photos")
             , 
              
              
              )

news/urls.py
from django.conf.urls import patterns, url

from news.views import  NewsDetailView, NewListView

urlpatterns = patterns('',
    url(r'(?P<slug>[\w-]+|)/$', NewsDetailView.as_view(),name= "story"),
    
    url(r'^$',NewListView.as_view(),name='news')               ,                 
   
                   
   # url(r'^about/$',views.about, name="about"),
    
)

polo/urls.py
from django.conf.urls import patterns, include, url
from sitemap import *
from django.contrib import admin
import publicpages.views
import nlsubscribers.views 
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'polo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
   # url('',publicpages.views.current_datetime,name="home"),
    
    url(r'^$', publicpages.views.current_datetime, name="home"),
    url(r'^about/$',publicpages.views.about, name="about"),
    url(r'^p1/$',publicpages.views.polo1, name="polo1"),
    url(r'^p2/$',publicpages.views.polo2, name="polo2"),
    url(r'^events/' ,include('events.urls',namespace="events")),
    url('^news/', include('news.urls',namespace='news')),
      url(r'^daguerre/', include('daguerre.urls')),
    url(r'^pages/' ,include('publicpages.urls', namespace="pages")),
    url(r'^teams/' ,include('teams.urls')),
    url(r'^sliders/' ,include('sliders.urls')),
    url(r'^multimedia/', include('mdias.urls',namespace='multimedia')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^manage/', include(admin.site.urls)),
    url(r'^nladd',nlsubscribers.views.nladd, name = "nladd"),
    
)


sitemaps = {
    'news':NewsSitemap,
    #'pages': FlatpageSitemap,
    #'site':SosaiSitemap(['home']),
    #['homepage_imprint', 'homepage_archive']
    #'site': Sitemap,
   
    'public': PublicPageSitemap
}


urlpatterns += patterns('',
                        (r'^sitemap\.xml', 'django.contrib.sitemaps.views.sitemap',
                         { 'sitemaps':sitemaps
     }),
    )
#for serving media files
from polo import settings

    
urlpatterns += patterns(
    'django.views.static',
    (r'media/(?P<path>.*)',
    'serve',
    {'document_root': settings.MEDIA_ROOT}), )


#for debug toolbar

if settings.SHOW_DEBUG_TOOLBAR:
    
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )
          

publicpages/urls.py
from django.conf.urls import patterns, url

from publicpages.views import about, current_datetime, StaticPage, ContactUs 


urlpatterns = patterns('',
   
    url(r'^about/$',about, name="about"),
    url(r'^$', current_datetime, name="home"),
    #url(r'^about/$',views.about, name="about"),
    url(r'^(?P<slug>\w+|)/$',StaticPage.as_view(), name = "page"),
    url(r'^contact',ContactUs.as_view(), name= "contact")
                        
)

nlsubscribers/models.py
from django.db import models
from datetime import datetime
# Create your models here.
class Nlsubscriber(models.Model):
    email = models.EmailField(unique=True)
    firstname = models.CharField(max_length=60, blank=True)
    lastname = models.CharField(max_length=60,blank=True)
    created = models.DateTimeField(default=datetime.now(),auto_now=False, auto_now_add=True)
    modified = models.DateTimeField(default=datetime.now(),auto_now=True, auto_now_add=False)
    class Meta:
        verbose_name = 'Newsletter Subscription list'
        verbose_name_plural ='Newsletter Subscription'
        
    
    
    
    def __unicode__(self):
        return self.email

nlsubscribers/forms.py
from django.forms import ModelForm
from nlsubscribers.models import Nlsubscriber

class NlsubscriberForm(ModelForm):
    class Meta:
        model = Nlsubscriber

nlsubscribers/views.py
from django.contrib import messages
from django.shortcuts import render,redirect

from nlsubscribers.models import Nlsubscriber


from nlsubscribers.forms import NlsubscriberForm


def nladd(request):
    if request.method == 'POST':
        form = NlsubscriberForm(request.POST)
        if form.is_valid():
            
            nlsub = form.save()
            messages.success(request, "Thank you for subscribing for our newsletters.")
            return redirect('/')
        else:
            messages.error(request, "Oops something went wrong, We could not take that information!")
            return redirect("/")
    else:
        messages.error(request, "Invalid request method")
        return redirect('/about/')
        

templates/header.html
 {% load staticfiles %}
 <header>
                <!-- End headerbox-->
                <div class="headerbox">
                    <div class="container">
                        <div class="row">
                            <!-- Logo-->
                            <div class="col-md-3 logo">
                                <a href="{% url "home" %}">                            
                                    <img src="{% static "img/logo.png" %}" class="logo_img">
                                </a>
                            </div>
                            <!-- End Logo-->

                            <!-- Adds Header-->
                            <div class="col-md-9 adds">
                            <div class="socila">
                            <div class="colsi">
                             <img src="{% static "img/phone.png" %}" class="logo_img">
                            </div>
                             <div class="colsi">
                            <h1><a href="tel:+2348098233966" style="color:#000;">+234 809 823 3966</a></h1>
                            </div>
                            </div>
                            </div>
                            <!-- End Adds Header-->
                        </div>
                    </div>
                </div>
                <!-- End headerbox-->  

                <!-- mainmenu-->
                <nav class="mainmenu">
                    <div class="container">
                        <!-- Menu-->
                        <ul class="sf-menu" id="menu">
                            <li class="selected">
                                <a href="{% url "home" %} ">Home</a>
                            </li>                                
                            <li class="current">
                                <a href="#">About</a>
                                <ul class="sub-current">
                                    <li>
                                        <a href="{% url "about" %}">History</a>
                                    </li>
                                    
                                    <li>
                                        <a href="{% url 'pages:page' 'trustees' %}">Trustees</a>
                                    </li>
                                     
                                </ul>
                            </li>
                            
                            
                             <li>
                                <a href="{% url 'pages:page' 'horseracing' %}">Horse Racing</a>
                                <div class="sf-mega">
                                    <div class="col-md-3">
                                        <h4>Prominent Challenge Cups</h4>
                                        <ul>                                                
                                            <li><a href="#"></a></li>
                                               <li><a href="#">Sultan Abubakar III Cup</a></li>
                                            <li><a href="#">Abuja Derby Cup</a></li>
                                         
                                          
                                       <li><a href="#">Queens Cup</a></li>
                                        </ul>
                                    </div>

                                    <div class="col-md-3">
                                      <h4>Sultan Abubakar Race Track</h4>
                                      <div class="img-hover">
                                         <img src="{% static "img/thumbs/racing_thumb.jpg" %}" alt="" class="img-responsive">
                                         <div class="overlay"><a href="{% url 'pages:page' 'horseracing' %}">+</a></div>
                                      </div>
                                    </div>

                                   <!-- <div class="col-md-3">
                                      <h4>Horsemen & Trainers</h4>
                                      <div class="img-hover">
                                         <img src="{% static 'img/blog/2.jpg' %}" alt="" class="img-responsive">
                                         <div class="overlay"><a href="#">+</a></div>
                                      </div>
                                    </div>-->
<!--
                                    <div class="col-md-3">
                                      <h4>Racing News</h4>
                                      <div class="img-hover">
                                         <img src="{% static 'img/blog/3.jpg' %}" alt="" class="img-responsive">
                                         <div class="overlay"><a href="#">+</a></div>
                                      </div>
                                    </div>
                                </div>-->
                            </li>
                            
                             <li>
                                <a href="{% url 'pages:page' 'tournaments' %} "> Polo</a>
                                <div class="sf-mega">
                                    <div class="col-md-3">
                                        <h4>Prominent Challenge Cups</h4>
                                        <ul>                                                
                                            <li><a href="{% url 'pages:page' 'tournaments' %}"></a></li>
                                           
                                            <li><a href="{% url 'pages:page' 'tournaments' %}">President Cup</a></li>
                                             <li><a href="{% url 'pages:page' 'tournaments' %}">Abuja Open Cup</a></li>
                                            
                                              <li><a href="{% url 'pages:page' 'tournaments' %}">Argentine Ambassador's Cup</a></li>
                                       <li><a href="#">Patrons Cup</a></li>
                                        
                                        </ul>
                                    </div>
                                     <div class="col-md-3">
                                      <h4>Exhilarating Polo </h4>
                                      <div class="img-hover">
                                         <img src="{% static 'img/thumbs/polo_thumb.jpg' %}" alt="" class="img-responsive">
                                          <div class="overlay"><a href="{% url 'pages:page' 'tournaments' %}">+</a></div>
                                      </div></div>
                                    <div class="col-md-3">
                                      <h4>Polo Tournaments</h4>
                                      <div class="img-hover">
                                              1212 Organizes a number of prestigious tournaments , horse racing events  and other equisterion
                                        tournaments. Prominent among which are:
                                         <div class="overlay"><a href="{% url 'pages:page' 'tournaments' %}">+</a></div>
                                      </div>
                                    </div>

                                    

                                    
                          
                                </div>
                            </li>
                            
                            
                             <li>
                                <a href="#">Multimedia & Events</a>
                                <div class="sf-mega">
                                    <div class="col-md-3">
                                         Documented  Moments & Times 
                                        <ul>                                                
                                            <li><a href="#"></a></li>
                                            <li><a href="#">Videos</a></li>
                                            <li><a href="{% url 'multimedia:photos' '' %}">Photos</a></li>
                                            <li><a href="#">Audio/Podcast</a></li>
                                             <li><a href="{% url 'events:events'%}">Events</a></li>
                                             
                                                                 </ul>
                                    </div>

                                    <div class="col-md-3">
                                      <h4>Upcoming Events</h4>
                                      <div class="img-hover">
                                         <img src="{% static "img/thumbs/trophies_thumb.jpg"%}" alt="" class="img-responsive">
                                         <div class="overlay"><a href="#">+</a></div>
                                      </div>
                                    </div>

                                    <div class="col-md-3">
                                      <h4>Recent Photos</h4>
                                      <div class="img-hover">
                                         <img src="{% static 'img/thumbs/carnival_thumb.jpg' %}" alt="" class="img-responsive">
                                         <div class="overlay"><a href="{% url 'multimedia:photos' 'recent' %}/">+</a></div>
                                      </div>
                                    </div>

                                    <div class="col-md-3">
                                      <h4>Recent Videos</h4>
                                      <div class="img-hover">
                                         <img src="{% static 'img/blog/3.jpg' %}" alt="" class="img-responsive">
                                         <div class="overlay"><a href="#">+</a></div>
                                      </div>
                                    </div>
                                </div>
                            </li>
                             <li>
                                <a href="{% url 'news:news' %}">News</a>
                            </li> 
                            <li class="current">
                                <a href="#">Facilities</a>
                                <ul class="sub-current">
                                    <li>
                                        <a href="{% url 'pages:page' 'race_track' %}">Horse Racing Track</a>
                                    </li>
                                    
                                     <li>
                                        <a href="{% url 'pages:page' 'parkinglot' %}">Parking Lot</a>
                                    </li>
                                    
                                    {% comment %}
                                    <li>
                                        <a href="{% url 'pages:page' 'terrace_lounge' %}">Terrace Lounge</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'pages:page' 'turf_club' %}">Turf Club</a>
                                    </li>
                                    
                                    <li>
                                        <a href="{% url 'pages:page' 'polo_field' %}">Polo Field</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'pages:page' 'stables' %}">Stables</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'pages:page' 'vet_services' %}">Vet Services</a>
                                    </li>
                                    {% endcomment %}
                                </ul>
                            </li> 
                            
                        
                            
                            <li>
                                <a href="{% url 'pages:contact' %}">Contact</a>
                            </li> 
                        </ul>
                        
                        
                        <!-- End Menu-->
                    </div>
                </nav>
                <!-- End mainmenu-->
            </header>

templates/nl_subscriber.html
 <div class="section-wide">
                    <div class="container">
                        <div class="row newsletter">
                            <div class="col-md-12">
                                <div class="text-center">
                                    <h2>Enter your e-mail and <span class="text-resalt">subscribe</span> to our newsletter.</h2>
                                    <p>We would only contact you with important details on our important activities...We hate SPAM!</p>
                                </div>
                                <form id="newsletterForm" action="{% url 'nladd' %}" method="post">
                                      {% csrf_token %}
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <i class="fa fa-envelope"></i>
                                                </span>
                                                <input class="form-control" placeholder="Firstname" name="firstname"  type="text" required="required">
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <i class="fa fa-envelope"></i>
                                                </span>
                                                <input class="form-control" placeholder="Lastname" name="lastname"  type="text" required="required">
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <i class="fa fa-envelope"></i>
                                                </span>
                                                <input class="form-control" placeholder="Your  Email" name="email"  type="email" required="required">
                                                <span class="input-group-btn">
                                                    <button class="btn btn-primary" type="submit" name="subscribe" >SIGN UP</button>
                                                 </span>
                                            </div>
                                        </div>
                                    </div>
                                </form>   
                                <div id="result-newsletter"></div>
                            </div>
                        </div>
                    </div>
                </div>  

templates/p1menu.html
  {% load staticfiles %}
<header id="header" class="header-default">
 
  <div class="shade">
     {% comment %}
      <div class="container fluid">
         <div class="row logo-container">
            
            <div class="col-lg-12" style="height: 140px">
                
               <a href="{% url 'home' %}" id="logo" style="margin-top: 5px">
                  <img src="{% static 'img/' %}logo.png" alt="1212" class="img-responsive center-block">
                  <!--img src="1212polo_files/logo.png" alt="" class="logo-retina" height="61" width="320"-->
               </a>
            </div>
         </div>
      </div>
      {% endcomment %}
       <div class="container fluid">
         <div class="row logo-container">
            
      <div class="col-lg-12" style="height: 240px; background:none; background-size: 100% auto; background-repeat: no-repeat">
                
                <!--div style="background-color: black; opacity: 0.8; height: 240px"-->
                <div>
               <a href="http://www.1212poloturf.com/" id="logo" class="logo" style="margin-top: 5px">
                  <img src="{% static "img/logos.png"%}" alt="1212" class="img-responsive center-block logo">
               </a>
                </div>
                <!--/div-->
             
            </div>
         </div>
      </div>
      <div class="sticky-wrapper">
         <nav role="navigation" id="navigation" class="text-center" style="background-color: #C0392B;margin-top: 0px;">
            <label id="nav-toggle" for="toggle-navigation" class="visible-xs"> <i class="fa fa-bars fa-lg"></i> </label>
            <input id="toggle-navigation" class="toggle-navigation-input" type="checkbox">
            <div class="container">
               <ul style="font-size: 0px;" id="menu-main-menu" class="menu">
                  <li style="font-size: 0px; margin-left: -20px;" id="menu-item-2030" class="menu-item menu-item-type-post_type menu-item-object-page   page_item page-item-1928   menu-item-2030">
                     <a href="{% url 'home' %}">Home</a>
                  </li>
                  <li style="font-size: 0px;margin-left: -20px;" id="menu-item-2029" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-parent-item menu-item-2029 dropdown-menu-sub-indicator">
                     <a href="#">About</a>
                     <ul style="visibility: hidden; display: none;" class="sub-menu">
                        <li id="menu-item-2032" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2032">
                           <a href="{% url 'pages:page' 'about' %}">History</a>
                        </li>
                        <li id="menu-item-2031" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2031">
                           <a href="{% url 'pages:page' 'trustees' %}">Trustees</a>
                        </li>
                        
                        <li id="menu-item-2031" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2031">
                           <a href="{% url 'pages:page' 'trustees' %}">Facilities</a>
                        </li>  
                     </ul>
                  </li>
                  {% comment %}
                  <li style="font-size: 0px;" id="menu-item-20251" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-parent-item menu-item-2025 dropdown-menu-sub-indicator">
                     <a href="#">Facilities</a>
                     <ul style="visibility: hidden; display: none;" class="sub-menu">
                        <li id="menu-item-20451" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2045">
                           <a href="#">Horse Racing Track</a>
                        </li>
                        <li id="menu-item-20441" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2044">
                           <a href="#">Parking Lot</a>
                        </li>
                     </ul>
                  </li>
                  {% endcomment %}
                  <li style="font-size: 0px;margin-left: -15px;" id="menu-item-19223" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-parent-item menu-item-1922 dropdown-menu-sub-indicator">
                     <a href="#">Polo</a>
                     <ul style="visibility: hidden; display: none;" class="sub-menu">
                          {% comment %}
                        <li id="menu-item-19273" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-parent-item menu-item-1927 dropdown-menu-sub-indicator">
                           <a href="#">Prominent Challenge Cups</a>
                           <ul style="visibility: hidden; display: none;" class="sub-menu">
                              <li id="menu-item-20583" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2058">
                                 <a href="#">President Cup</a>
                              </li>
                              <li id="menu-item-20537" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2057">
                                 <a href="#">Abuja Open Cup</a>
                              </li>
                              <li id="menu-item-20602" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2057">
                                 <a href="#">Patron Cup</a>
                              </li>
                              <li id="menu-item-2059" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2059">
                                 <a href="#">Argentine Ambassador Cup</a>
                              </li>
                           </ul>
                        </li>
                           {% endcomment %}
                        <li id="menu-item-2021" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2050">
                           <a href="#">Tournament</a>
                        </li>
                         <li id="menu-item-2021" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2050">
                           <a href="#">Upcoming Events</a>
                        </li>
                     </ul>
                  </li>
                  <li style="font-size: 0px;margin-left: -10px;" id="menu-item-19221" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-parent-item menu-item-1922 dropdown-menu-sub-indicator">
                     <a href="#">Horseracing</a>
                     <ul style="visibility: hidden; display: none;" class="sub-menu">
                        <li id="menu-item-19271" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-parent-item menu-item-1927 dropdown-menu-sub-indicator">
                           <a href="#">Prominent Challenge Cups</a>
                           <ul style="visibility: hidden; display: none;" class="sub-menu">
                              <li id="menu-item-20581" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2058">
                                 <a href="#">Sultan Abubakar III Cup</a>
                              </li>
                              <li id="menu-item-20571" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2057">
                                 <a href="#">Abuja Derby Cup</a>
                              </li>
                              <li id="menu-item-20601" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2057">
                                 <a href="#">Queen's Cup</a>
                              </li>
                           </ul>
                        </li>
                        <li id="menu-item-20501" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2050">
                           <a href="#">Sultan Abubakar Race Track</a>
                        </li>
                     </ul>
                  </li>
                  <li style="font-size: 0px;margin-left:  134px;" id="menu-item-2025" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-parent-item menu-item-2025 dropdown-menu-sub-indicator">
                     <a href="{% url 'events:events' %}">Events</a>
                     <ul style="visibility: hidden; display: none;" class="sub-menu">
                        <li id="menu-item-2045" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2045">
                           <a href="{% url 'events:events' %}">Events</a>
                        </li>
                        <li id="menu-item-20453" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2045">
                           <a href="{% url 'multimedia:photos' ''  %}">Photo</a>
                        </li>
                        <li id="menu-item-2044" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2044">
                           <a href="#">Video</a>
                        </li>
                     </ul>
                  </li>
                  <li style="font-size: 0px;" id="menu-item-20331" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2033">
                     <a href="{% url 'multimedia:photos' ''  %}">Gallery</a>
                  </li>
                  
                  <li style="font-size: 0px;" id="menu-item-2028" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2028">
                     <a href="{% url 'news:news' %}">News</a>
                  </li>
                  <li style="font-size: 0px;" id="menu-item-2033" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2033">
                     <a href="{% url 'pages:contact' %}">Contact</a>
                  </li>
               </ul>
            </div>
         </nav>
        
      </div>
      
   </div>
   </div>

</header>

 